name: 'Github Actions'
description: 'My first Github Action'
author: 'Saranya'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  TENOR_TOKEN:
    description: 'Tenor API token'
    required: true

runs:
  using: 'node22'
  main: 'dist/index.js'